In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
df=pd.read_csv('/content/drive/MyDrive/Data_sets/hacktrain.csv')
df

Mounted at /content/drive

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,...,NaN,-1043.160,-1942.490,267.138,NaN,NaN,211.328,-2203.020,-1180.19,433.906
1,1,2,water,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,...,NaN,-933.934,-625.385,120.059,364.858,476.972,220.878,-2250.000,-1360.56,524.075
2,3,4,water,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,...,-1025.880,368.622,NaN,-1227.800,304.621,NaN,369.214,-2202.120,NaN,-1343.550
3,4,5,water,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,...,-1813.950,155.624,NaN,-924.073,432.150,282.833,298.320,-2197.360,NaN,-826.727
4,7,8,water,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.650,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,...,1117.740,1176.600,1044.110,NaN,369.082,465.843,362.882,979.795,NaN,433.659
7996,10538,10539,impervious,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,...,984.634,2128.970,1379.660,NaN,762.633,485.204,446.724,771.747,1589.06,506.936
7997,10541,10542,impervious,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.000,1818.650,2501.72,1247.770
7998,10542,10543,impervious,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,NaN,3759.710,NaN,388.346
7999,10544,10545,impervious,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,...,7352.570,3289.860,3729.150,1994.980,NaN,5299.900,NaN,5983.130,1249.71,2424.230

In [2]:
import pandas as pd
import numpy as np

# Just to be safe, reset column names if needed
df.columns = df.columns.astype(str)

# Confirm that 'class' and 'ID' are present
print(df.columns.tolist())

# Save and drop non-numeric columns
if 'class' in df.columns and 'ID' in df.columns:
    df_non_numeric = df[['ID', 'class']]  # Keep non-numeric part
    df_numeric = df.drop(columns=['ID', 'class'])  # Numeric part
else:
    raise KeyError("Make sure 'ID' and 'class' columns exist in df")

# Fill NaNs in numeric columns using class-wise group mean
df_numeric_filled = df_numeric.groupby(df_non_numeric['class']).transform(lambda x: x.fillna(x.mean()))

# Combine cleaned numeric data with original non-numeric
df_cleaned = pd.concat([df_non_numeric, df_numeric_filled], axis=1)

# Done
df_cleaned

['Unnamed: 0', 'ID', 'class', '20150720_N', '20150602_N', '20150517_N', '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N', '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N', '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N', '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N', '20140218_N', '20140202_N', '20140117_N', '20140101_N']

,ID,class,Unnamed: 0,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,1,water,0,637.5950,658.668000,-1882.030000,-1924.360000,997.904000,-1739.990000,630.087000,...,2013.680657,-1043.160,-1942.490000,267.138000,1127.101172,987.976689,211.328000,-2203.020,-1180.190000,433.906
1,2,water,1,634.2400,593.705000,-1625.790000,-1672.320000,914.198000,-692.386000,707.626000,...,2013.680657,-933.934,-625.385000,120.059000,364.858000,476.972000,220.878000,-2250.000,-1360.560000,524.075
2,4,water,3,58.0174,-1599.160000,1101.121938,-1052.630000,1037.900596,-1564.630000,1131.306331,...,-1025.880000,368.622,1217.060015,-1227.800000,304.621000,987.976689,369.214000,-2202.120,973.156134,-1343.550
3,5,water,4,72.5180,1628.972375,380.436000,-1256.930000,515.805000,-1413.180000,-802.942000,...,-1813.950000,155.624,1217.060015,-924.073000,432.150000,282.833000,298.320000,-2197.360,973.156134,-826.727
4,8,water,7,1136.4400,1628.972375,1101.121938,1647.830000,1935.800000,931.040746,2158.980000,...,1535.000000,1959.430,-279.317000,-384.915000,-113.406000,1020.720000,1660.650000,-116.801,-568.050000,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10538,impervious,10537,1207.7000,984.620000,1703.133611,1166.250000,937.478000,1072.700000,823.896000,...,1117.740000,1176.600,1044.110000,1461.677426,369.082000,465.843000,362.882000,979.795,1685.555382,433.659
7996,10539,impervious,10538,2170.3500,1419.720000,1361.000000,1478.710000,983.911000,1262.110000,1422.860000,...,984.634000,2128.970,1379.660000,1461.677426,762.633000,485.204000,446.724000,771.747,1589.060000,506.936
7997,10542,impervious,10541,1895.6800,1454.740000,1703.133611,1033.560000,1930.380000,1057.150000,1471.600000,...,888.408000,2093.020,1232.110000,1190.830000,1441.460000,1170.880000,1095.000000,1818.650,2501.720000,1247.770
7998,10543,impervious,10542,3465.7400,1283.320000,413.412000,4391.050000,1146.820000,4473.050000,1614.750000,...,5833.760000,4047.320,4515.800000,433.177000,277.296000,744.143000,876.051986,3759.710,1685.555382,388.346
7999,10545,impervious,10544,6941.1900,1667.870000,5084.780000,2075.706549,1588.950000,5978.190000,1905.891489,...,7352.570000,3289.860,3729.150000,1994.980000,1123.753846,5299.900000,876.051986,5983.130,1249.710000,2424.230

In [3]:
from sklearn.preprocessing import LabelEncoder

# drop the ID column:
df_cleaned.drop(columns=['ID'], inplace=True)
# drop the Unammed column:
df_cleaned.drop(columns=['Unnamed: 0'],inplace =True)
# Give the class labels:
label_encoder = LabelEncoder()
df_cleaned['class'] = label_encoder.fit_transform(df_cleaned['class'])
df_cleaned

,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,5,637.5950,658.668000,-1882.030000,-1924.360000,997.904000,-1739.990000,630.087000,527.135156,-1325.64000,...,2013.680657,-1043.160,-1942.490000,267.138000,1127.101172,987.976689,211.328000,-2203.020,-1180.190000,433.906
1,5,634.2400,593.705000,-1625.790000,-1672.320000,914.198000,-692.386000,707.626000,-1670.590000,-1408.64000,...,2013.680657,-933.934,-625.385000,120.059000,364.858000,476.972000,220.878000,-2250.000,-1360.560000,524.075
2,5,58.0174,-1599.160000,1101.121938,-1052.630000,1037.900596,-1564.630000,1131.306331,729.790000,-3162.14000,...,-1025.880000,368.622,1217.060015,-1227.800000,304.621000,987.976689,369.214000,-2202.120,973.156134,-1343.550
3,5,72.5180,1628.972375,380.436000,-1256.930000,515.805000,-1413.180000,-802.942000,683.254000,-2829.40000,...,-1813.950000,155.624,1217.060015,-924.073000,432.150000,282.833000,298.320000,-2197.360,973.156134,-826.727
4,5,1136.4400,1628.972375,1101.121938,1647.830000,1935.800000,931.040746,2158.980000,527.135156,1242.87000,...,1535.000000,1959.430,-279.317000,-384.915000,-113.406000,1020.720000,1660.650000,-116.801,-568.050000,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,3,1207.7000,984.620000,1703.133611,1166.250000,937.478000,1072.700000,823.896000,943.698000,944.61900,...,1117.740000,1176.600,1044.110000,1461.677426,369.082000,465.843000,362.882000,979.795,1685.555382,433.659
7996,3,2170.3500,1419.720000,1361.000000,1478.710000,983.911000,1262.110000,1422.860000,1401.970000,1372.68000,...,984.634000,2128.970,1379.660000,1461.677426,762.633000,485.204000,446.724000,771.747,1589.060000,506.936
7997,3,1895.6800,1454.740000,1703.133611,1033.560000,1930.380000,1057.150000,1471.600000,1861.231092,2693.63000,...,888.408000,2093.020,1232.110000,1190.830000,1441.460000,1170.880000,1095.000000,1818.650,2501.720000,1247.770
7998,3,3465.7400,1283.320000,413.412000,4391.050000,1146.820000,4473.050000,1614.750000,770.469000,2101.29442,...,5833.760000,4047.320,4515.800000,433.177000,277.296000,744.143000,876.051986,3759.710,1685.555382,388.346
7999,3,6941.1900,1667.870000,5084.780000,2075.706549,1588.950000,5978.190000,1905.891489,3068.030000,6471.47000,...,7352.570000,3289.860,3729.150000,1994.980000,1123.753846,5299.900000,876.051986,5983.130,1249.710000,2424.230

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = df_cleaned.drop(columns=['class'])
y = df_cleaned['class']

0       5
1       5
2       5
3       5
4       5
       ..
7995    3
7996    3
7997    3
7998    3
7999    3
Name: class, Length: 8000, dtype: int64

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical






# For multi-class classification
if len(np.unique(y)) > 2:
    y = to_categorical(y)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build the model
model = Sequential()
model.add(Dense(60, input_dim=X_train.shape[1], activation='relu'))  # Input layer
model.add(Dense(30, activation='relu'))  # Hidden layer
model.add(Dense(10, activation='relu'))  # Hidden layer

model.add(Dense(y_train.shape[1] if len(y.shape) > 1 else 1, activation='softmax' if len(y.shape) > 1 else 'sigmoid'))  # Output layer

# Compile the model
model.compile(
    loss='categorical_crossentropy' if len(y.shape) > 1 else 'binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6622 - loss: 0.9915 - val_accuracy: 0.9141 - val_loss: 0.3315
Epoch 2/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8947 - loss: 0.3384 - val_accuracy: 0.9281 - val_loss: 0.2464
Epoch 3/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9211 - loss: 0.2406 - val_accuracy: 0.9344 - val_loss: 0.2161
Epoch 4/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9273 - loss: 0.2193 - val_accuracy: 0.9438 - val_loss: 0.1993
Epoch 5/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9353 - loss: 0.1983 - val_accuracy: 0.9531 - val_loss: 0.1732
Epoch 6/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9464 - loss: 0.1725 - val_accuracy: 0.9547 - val_loss: 0.1658
Epoch 7/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9532 - loss: 0.1531 - val_accuracy: 0.9531 - val_loss: 0.1550
Epoch 8/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9509 - loss: 0.1495 - val_accuracy: 0.9547 - val_loss: 0.1609
Epoch 9/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9618 - loss: 0.1213 - val_accuracy: 0.9594 - val_loss: 0.1497
Epoch 10/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9640 - loss: 0.1161 - val_accuracy: 0.9563 - val_loss: 0.1412
Epoch 11/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9633 - loss: 0.1153 - val_accuracy: 0.9563 - val_loss: 0.1471
Epoch 12/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9669 - loss: 0.1058 - val_accuracy: 0.9578 - val_loss: 0.1440
Epoch 13/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9752 - loss: 0.0967 - val_accuracy: 0.9563 - val_loss: 0.1420
Epoch 14/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9740 - loss: 0.0847 - val_accuracy: 0.9578 - val_loss: 0.1499
Epoch 15/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9733 - loss: 0.0858 - val_accuracy: 0.9672 - val_loss: 0.1349
Epoch 16/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9734 - loss: 0.0832 - val_accuracy: 0.9641 - val_loss: 0.1437
Epoch 17/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9803 - loss: 0.0702 - val_accuracy: 0.9641 - val_loss: 0.1440
Epoch 18/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9834 - loss: 0.0597 - val_accuracy: 0.9703 - val_loss: 0.1407
Epoch 19/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9842 - loss: 0.0559 - val_accuracy: 0.9672 - val_loss: 0.1483
Epoch 20/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9835 - loss: 0.0610 - val_accuracy: 0.9625 - val_loss: 0.1482
Epoch 21/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9845 - loss: 0.0564 - val_accuracy: 0.9703 - val_loss: 0.1481
Epoch 22/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9883 - loss: 0.0502 - val_accuracy: 0.9656 - val_loss: 0.1516
Epoch 23/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9869 - loss: 0.0531 - val_accuracy: 0.9688 - val_loss: 0.1538
Epoch 24/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9913 - loss: 0.0408 - val_accuracy: 0.9656 - val_loss: 0.1637
Epoch 25/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9907 - loss: 0.0423 - val_accuracy: 0.9656 - val_loss: 0.1657
Epoch 26/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9930 - loss: 0.0313 - val_accuracy: 0.9609 - val_loss: 0.1851
Epoch 27/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9892 - loss: 0.0376 - val_accuracy: 0.9625 - val_loss: 0.1722
Epoch 28/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9923 - loss: 0.0339 - val_accuracy: 0.9641 - val_loss: 0.1984
Epoch 29/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9910 - loss: 0.0343 - val_accuracy: 0.9641 - val_loss: 0.1772
Epoch 30/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9924 - loss: 0.0313 - val_accuracy: 0.9625 - val_loss: 0.1836
Epoch 31/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9936 - loss: 0.0252 - val_accuracy: 0.9625 - val_loss: 0.1912
Epoch 32/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9962 - loss: 0.0179 - val_accuracy: 0.9641 - val_loss: 0.2025
Epoch 33/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9938 - loss: 0.0242 - val_accuracy: 0.9563 - val_loss: 0.2122
Epoch 34/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9916 - loss: 0.0284 - val_accuracy: 0.9594 - val_loss: 0.2104
Epoch 35/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9962 - loss: 0.0182 - val_accuracy: 0.9672 - val_loss: 0.2126
Epoch 36/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9955 - loss: 0.0192 - val_accuracy: 0.9578 - val_loss: 0.2305
Epoch 37/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9960 - loss: 0.0187 - val_accuracy: 0.9609 - val_loss: 0.2279
Epoch 38/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9972 - loss: 0.0142 - val_accuracy: 0.9594 - val_loss: 0.2473
Epoch 39/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9961 - loss: 0.0145 - val_accuracy: 0.9641 - val_loss: 0.2388
Epoch 40/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0090 - val_accuracy: 0.9594 - val_loss: 0.2427
Epoch 41/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9967 - loss: 0.0139 - val_accuracy: 0.9656 - val_loss: 0.2418
Epoch 42/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9987 - loss: 0.0097 - val_accuracy: 0.9625 - val_loss: 0.2910
Epoch 43/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9982 - loss: 0.0112 - val_accuracy: 0.9641 - val_loss: 0.2545
Epoch 44/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9990 - loss: 0.0075 - val_accuracy: 0.9641 - val_loss: 0.2707
Epoch 45/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9988 - loss: 0.0077 - val_accuracy: 0.9625 - val_loss: 0.2732
Epoch 46/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9990 - loss: 0.0061 - val_accuracy: 0.9656 - val_loss: 0.2665
Epoch 47/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9993 - loss: 0.0063 - val_accuracy: 0.9656 - val_loss: 0.2679
Epoch 48/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9979 - loss: 0.0074 - val_accuracy: 0.9641 - val_loss: 0.2953
Epoch 49/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0043 - val_accuracy: 0.9609 - val_loss: 0.2757
Epoch 50/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9996 - loss: 0.0041 - val_accuracy: 0.9641 - val_loss: 0.2988
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9599 - loss: 0.3088
Test Accuracy: 95.25%

In [18]:
# Test the data:
test_df=pd.read_csv('/content/drive/MyDrive/Data_sets/hacktest.csv')

ID=test_df['ID']
# drop the ID column:
test_df.drop(columns=['ID'], inplace=True)
# drop the Unammed column:
test_df.drop(columns=['Unnamed: 0'],inplace =True)
test_df

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,7466.4200,413.162,5761.000,5625.45,489.4030,3923.84,3097.110,6766.42000,2829.130,6742.570,...,801.184,927.115,4704.14,6378.42,340.949,2695.5700,527.268,4736.75,601.843,6639.760
1,7235.2600,6037.350,1027.560,6085.14,1618.0500,6668.54,2513.990,1051.69000,7268.220,6908.180,...,5533.470,5103.040,5216.12,4885.27,4366.790,1234.1400,3298.110,6942.68,1070.440,842.101
2,7425.0800,6969.980,1177.940,7408.93,861.0610,7644.43,814.458,1504.29000,7002.630,6086.560,...,1981.390,6204.540,7021.69,5704.41,4897.450,1789.9900,2206.100,6928.93,1036.560,831.441
3,7119.1200,1731.620,6311.930,6441.61,465.9790,7128.42,1649.120,6935.22000,2176.800,690.408,...,959.344,5794.150,1045.57,5572.90,586.287,685.9060,1287.000,6734.72,824.584,6883.610
4,7519.5500,8130.260,1482.540,7879.53,1001.2100,7937.60,4122.530,1094.51000,7951.440,8001.350,...,7636.070,6996.760,7413.43,4596.13,4511.700,1413.5200,3283.940,7937.68,1857.800,1336.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,-1673.7400,-2514.480,-2451.190,-2738.44,64.4464,-2275.03,-2881.100,-4738.97000,-4293.570,-4402.210,...,-2257.890,-2582.420,-1699.10,-2295.30,306.483,209.4030,221.920,-4885.15,-2630.590,356.233
2841,-96.8233,-412.727,-1795.400,-2363.82,-2168.1900,-2162.68,-3155.740,-4416.11000,-5648.660,-5193.280,...,-3991.910,-2614.910,-2109.84,-2687.18,-2853.890,71.3402,-86.414,-5109.01,324.637,-4316.580
2842,-2364.6000,-155.592,-1422.090,-1713.40,465.6220,-2230.40,-3088.730,-5010.32000,-4211.420,-3354.430,...,-2484.500,-1756.080,-3820.43,-1988.23,433.852,291.8000,254.548,-4259.30,412.115,-1170.750
2843,-3004.6300,-1217.120,180.122,-1113.89,438.4180,-2442.51,-3210.560,-3237.74000,-192.857,-2857.540,...,-3291.490,-2018.450,-3472.65,-3109.07,511.792,369.0970,276.948,-5574.51,298.739,460.419
2844,-2975.1000,-1129.790,463.748,-5355.40,193.5110,-2590.16,-3113.520,-2.38883,-1248.450,328.306,...,-3058.230,-2276.180,-3335.00,-2929.19,-1007.500,271.0580,307.997,-5453.33,307.495,417.124

In [19]:


# 1. Preprocess the test data same as training (scaling)
test_df = scaler.transform(test_df)  # use the same scaler fitted on X_train

# 2. Make predictions using the trained model
y_pred_probs = model.predict(test_df)  # raw probabilities

# 3. Convert probabilities to class labels

# Multi-class classification
y_pred = np.argmax(y_pred_probs, axis=1)
y_pred

89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([0, 4, 4, ..., 5, 5, 1])

In [20]:
# decode the numbers to labels:
y_decoded = label_encoder.inverse_transform(y_pred)
# create a dataframe for result:
result = pd.DataFrame({
    'ID': ID,
    'class': y_decoded
})
result

        ID    class
0        1     farm
1        2  orchard
2        3  orchard
3        4     farm
4        5  orchard
...    ...      ...
2840  2841    water
2841  2842    water
2842  2843    water
2843  2844    water
2844  2845   forest

[2845 rows x 2 columns]

In [22]:
result.to_csv("submission.csv", index=False) #this file will appear under the output section of the right navbar. You need to submit this csv file